kind: pipeline
name: default

steps:
- name: Python&JavaforremoteIssue122ssW
  image: carvk/java_python:openjdk15_python

  commands:
    - pip install -r requirements.txt
    - pytest -v -s
type: docker

